/**
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.tests;

import cl.ejemplo.entidades.entidades.Atributo;
import cl.ejemplo.entidades.entidades.Entidad;
import cl.ejemplo.entidades.entidades.Model;
import cl.ejemplo.entidades.tests.EntidadesInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Assert;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(EntidadesInjectorProvider.class)
@SuppressWarnings("all")
public class EntidadesParsingTest {
  @Inject
  @Extension
  private ParseHelper<Model> _parseHelper;
  
  @Test
  public void testModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.newLine();
      _builder.append("entidad MiEntidad {");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("MiEntidad atributo;");
      _builder.newLine();
      _builder.append("}\t");
      _builder.newLine();
      final Model model = this._parseHelper.parse(_builder);
      final Entidad entidad = model.getEntidades().get(0);
      Assert.assertEquals("MiEntidad", entidad.getName());
      final Atributo atributo = entidad.getAtributos().get(0);
      Assert.assertEquals("atributo", atributo.getName());
      Entidad _entidad = atributo.getTipo().getEntidad();
      Assert.assertEquals("MiEntidad", ((Entidad) _entidad).getName());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
