/*
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntidadesRuntimeModule extends AbstractEntidadesRuntimeModule {
}
