/*
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class EntidadesScopeProvider extends AbstractEntidadesScopeProvider {

}
