/*
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.ui.tests;

import cl.ejemplo.entidades.ui.internal.EntidadesActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EntidadesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EntidadesActivator.getInstance().getInjector("cl.ejemplo.entidades.Entidades");
	}

}
