/*
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEntidadesScopeProvider extends DelegatingScopeProvider {
}
