/*
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EntidadesUiModule extends AbstractEntidadesUiModule {

	public EntidadesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
