/**
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.entidades;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atributo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cl.ejemplo.entidades.entidades.Atributo#getTipo <em>Tipo</em>}</li>
 *   <li>{@link cl.ejemplo.entidades.entidades.Atributo#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getAtributo()
 * @model
 * @generated
 */
public interface Atributo extends EObject
{
  /**
   * Returns the value of the '<em><b>Tipo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' containment reference.
   * @see #setTipo(TipoAtributo)
   * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getAtributo_Tipo()
   * @model containment="true"
   * @generated
   */
  TipoAtributo getTipo();

  /**
   * Sets the value of the '{@link cl.ejemplo.entidades.entidades.Atributo#getTipo <em>Tipo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' containment reference.
   * @see #getTipo()
   * @generated
   */
  void setTipo(TipoAtributo value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getAtributo_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cl.ejemplo.entidades.entidades.Atributo#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Atributo
