/**
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.entidades;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see cl.ejemplo.entidades.entidades.EntidadesFactory
 * @model kind="package"
 * @generated
 */
public interface EntidadesPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "entidades";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ejemplo.cl/entidades/Entidades";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "entidades";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EntidadesPackage eINSTANCE = cl.ejemplo.entidades.entidades.impl.EntidadesPackageImpl.init();

  /**
   * The meta object id for the '{@link cl.ejemplo.entidades.entidades.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cl.ejemplo.entidades.entidades.impl.ModelImpl
   * @see cl.ejemplo.entidades.entidades.impl.EntidadesPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Entidades</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENTIDADES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link cl.ejemplo.entidades.entidades.impl.EntidadImpl <em>Entidad</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cl.ejemplo.entidades.entidades.impl.EntidadImpl
   * @see cl.ejemplo.entidades.entidades.impl.EntidadesPackageImpl#getEntidad()
   * @generated
   */
  int ENTIDAD = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__NAME = 0;

  /**
   * The feature id for the '<em><b>Super Tipo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__SUPER_TIPO = 1;

  /**
   * The feature id for the '<em><b>Atributos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__ATRIBUTOS = 2;

  /**
   * The number of structural features of the '<em>Entidad</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link cl.ejemplo.entidades.entidades.impl.AtributoImpl <em>Atributo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cl.ejemplo.entidades.entidades.impl.AtributoImpl
   * @see cl.ejemplo.entidades.entidades.impl.EntidadesPackageImpl#getAtributo()
   * @generated
   */
  int ATRIBUTO = 2;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__TIPO = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__NAME = 1;

  /**
   * The number of structural features of the '<em>Atributo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link cl.ejemplo.entidades.entidades.impl.TipoAtributoImpl <em>Tipo Atributo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cl.ejemplo.entidades.entidades.impl.TipoAtributoImpl
   * @see cl.ejemplo.entidades.entidades.impl.EntidadesPackageImpl#getTipoAtributo()
   * @generated
   */
  int TIPO_ATRIBUTO = 3;

  /**
   * The feature id for the '<em><b>Entidad</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_ATRIBUTO__ENTIDAD = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_ATRIBUTO__ARRAY = 1;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_ATRIBUTO__LENGTH = 2;

  /**
   * The number of structural features of the '<em>Tipo Atributo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_ATRIBUTO_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link cl.ejemplo.entidades.entidades.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see cl.ejemplo.entidades.entidades.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link cl.ejemplo.entidades.entidades.Model#getEntidades <em>Entidades</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entidades</em>'.
   * @see cl.ejemplo.entidades.entidades.Model#getEntidades()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Entidades();

  /**
   * Returns the meta object for class '{@link cl.ejemplo.entidades.entidades.Entidad <em>Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidad</em>'.
   * @see cl.ejemplo.entidades.entidades.Entidad
   * @generated
   */
  EClass getEntidad();

  /**
   * Returns the meta object for the attribute '{@link cl.ejemplo.entidades.entidades.Entidad#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see cl.ejemplo.entidades.entidades.Entidad#getName()
   * @see #getEntidad()
   * @generated
   */
  EAttribute getEntidad_Name();

  /**
   * Returns the meta object for the reference '{@link cl.ejemplo.entidades.entidades.Entidad#getSuperTipo <em>Super Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Tipo</em>'.
   * @see cl.ejemplo.entidades.entidades.Entidad#getSuperTipo()
   * @see #getEntidad()
   * @generated
   */
  EReference getEntidad_SuperTipo();

  /**
   * Returns the meta object for the containment reference list '{@link cl.ejemplo.entidades.entidades.Entidad#getAtributos <em>Atributos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Atributos</em>'.
   * @see cl.ejemplo.entidades.entidades.Entidad#getAtributos()
   * @see #getEntidad()
   * @generated
   */
  EReference getEntidad_Atributos();

  /**
   * Returns the meta object for class '{@link cl.ejemplo.entidades.entidades.Atributo <em>Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atributo</em>'.
   * @see cl.ejemplo.entidades.entidades.Atributo
   * @generated
   */
  EClass getAtributo();

  /**
   * Returns the meta object for the containment reference '{@link cl.ejemplo.entidades.entidades.Atributo#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo</em>'.
   * @see cl.ejemplo.entidades.entidades.Atributo#getTipo()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_Tipo();

  /**
   * Returns the meta object for the attribute '{@link cl.ejemplo.entidades.entidades.Atributo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see cl.ejemplo.entidades.entidades.Atributo#getName()
   * @see #getAtributo()
   * @generated
   */
  EAttribute getAtributo_Name();

  /**
   * Returns the meta object for class '{@link cl.ejemplo.entidades.entidades.TipoAtributo <em>Tipo Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipo Atributo</em>'.
   * @see cl.ejemplo.entidades.entidades.TipoAtributo
   * @generated
   */
  EClass getTipoAtributo();

  /**
   * Returns the meta object for the reference '{@link cl.ejemplo.entidades.entidades.TipoAtributo#getEntidad <em>Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entidad</em>'.
   * @see cl.ejemplo.entidades.entidades.TipoAtributo#getEntidad()
   * @see #getTipoAtributo()
   * @generated
   */
  EReference getTipoAtributo_Entidad();

  /**
   * Returns the meta object for the attribute '{@link cl.ejemplo.entidades.entidades.TipoAtributo#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see cl.ejemplo.entidades.entidades.TipoAtributo#isArray()
   * @see #getTipoAtributo()
   * @generated
   */
  EAttribute getTipoAtributo_Array();

  /**
   * Returns the meta object for the attribute '{@link cl.ejemplo.entidades.entidades.TipoAtributo#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see cl.ejemplo.entidades.entidades.TipoAtributo#getLength()
   * @see #getTipoAtributo()
   * @generated
   */
  EAttribute getTipoAtributo_Length();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EntidadesFactory getEntidadesFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link cl.ejemplo.entidades.entidades.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cl.ejemplo.entidades.entidades.impl.ModelImpl
     * @see cl.ejemplo.entidades.entidades.impl.EntidadesPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Entidades</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENTIDADES = eINSTANCE.getModel_Entidades();

    /**
     * The meta object literal for the '{@link cl.ejemplo.entidades.entidades.impl.EntidadImpl <em>Entidad</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cl.ejemplo.entidades.entidades.impl.EntidadImpl
     * @see cl.ejemplo.entidades.entidades.impl.EntidadesPackageImpl#getEntidad()
     * @generated
     */
    EClass ENTIDAD = eINSTANCE.getEntidad();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTIDAD__NAME = eINSTANCE.getEntidad_Name();

    /**
     * The meta object literal for the '<em><b>Super Tipo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTIDAD__SUPER_TIPO = eINSTANCE.getEntidad_SuperTipo();

    /**
     * The meta object literal for the '<em><b>Atributos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTIDAD__ATRIBUTOS = eINSTANCE.getEntidad_Atributos();

    /**
     * The meta object literal for the '{@link cl.ejemplo.entidades.entidades.impl.AtributoImpl <em>Atributo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cl.ejemplo.entidades.entidades.impl.AtributoImpl
     * @see cl.ejemplo.entidades.entidades.impl.EntidadesPackageImpl#getAtributo()
     * @generated
     */
    EClass ATRIBUTO = eINSTANCE.getAtributo();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__TIPO = eINSTANCE.getAtributo_Tipo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUTO__NAME = eINSTANCE.getAtributo_Name();

    /**
     * The meta object literal for the '{@link cl.ejemplo.entidades.entidades.impl.TipoAtributoImpl <em>Tipo Atributo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cl.ejemplo.entidades.entidades.impl.TipoAtributoImpl
     * @see cl.ejemplo.entidades.entidades.impl.EntidadesPackageImpl#getTipoAtributo()
     * @generated
     */
    EClass TIPO_ATRIBUTO = eINSTANCE.getTipoAtributo();

    /**
     * The meta object literal for the '<em><b>Entidad</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIPO_ATRIBUTO__ENTIDAD = eINSTANCE.getTipoAtributo_Entidad();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO_ATRIBUTO__ARRAY = eINSTANCE.getTipoAtributo_Array();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO_ATRIBUTO__LENGTH = eINSTANCE.getTipoAtributo_Length();

  }

} //EntidadesPackage
