/**
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.entidades;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entidad</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cl.ejemplo.entidades.entidades.Entidad#getName <em>Name</em>}</li>
 *   <li>{@link cl.ejemplo.entidades.entidades.Entidad#getSuperTipo <em>Super Tipo</em>}</li>
 *   <li>{@link cl.ejemplo.entidades.entidades.Entidad#getAtributos <em>Atributos</em>}</li>
 * </ul>
 *
 * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getEntidad()
 * @model
 * @generated
 */
public interface Entidad extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getEntidad_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cl.ejemplo.entidades.entidades.Entidad#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Super Tipo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Tipo</em>' reference.
   * @see #setSuperTipo(Entidad)
   * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getEntidad_SuperTipo()
   * @model
   * @generated
   */
  Entidad getSuperTipo();

  /**
   * Sets the value of the '{@link cl.ejemplo.entidades.entidades.Entidad#getSuperTipo <em>Super Tipo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Tipo</em>' reference.
   * @see #getSuperTipo()
   * @generated
   */
  void setSuperTipo(Entidad value);

  /**
   * Returns the value of the '<em><b>Atributos</b></em>' containment reference list.
   * The list contents are of type {@link cl.ejemplo.entidades.entidades.Atributo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atributos</em>' containment reference list.
   * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getEntidad_Atributos()
   * @model containment="true"
   * @generated
   */
  EList<Atributo> getAtributos();

} // Entidad
