/**
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.entidades;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cl.ejemplo.entidades.entidades.Model#getEntidades <em>Entidades</em>}</li>
 * </ul>
 *
 * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Entidades</b></em>' containment reference list.
   * The list contents are of type {@link cl.ejemplo.entidades.entidades.Entidad}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entidades</em>' containment reference list.
   * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getModel_Entidades()
   * @model containment="true"
   * @generated
   */
  EList<Entidad> getEntidades();

} // Model
