/**
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.entidades;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tipo Atributo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cl.ejemplo.entidades.entidades.TipoAtributo#getEntidad <em>Entidad</em>}</li>
 *   <li>{@link cl.ejemplo.entidades.entidades.TipoAtributo#isArray <em>Array</em>}</li>
 *   <li>{@link cl.ejemplo.entidades.entidades.TipoAtributo#getLength <em>Length</em>}</li>
 * </ul>
 *
 * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getTipoAtributo()
 * @model
 * @generated
 */
public interface TipoAtributo extends EObject
{
  /**
   * Returns the value of the '<em><b>Entidad</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entidad</em>' reference.
   * @see #setEntidad(Entidad)
   * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getTipoAtributo_Entidad()
   * @model
   * @generated
   */
  Entidad getEntidad();

  /**
   * Sets the value of the '{@link cl.ejemplo.entidades.entidades.TipoAtributo#getEntidad <em>Entidad</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entidad</em>' reference.
   * @see #getEntidad()
   * @generated
   */
  void setEntidad(Entidad value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute.
   * @see #setArray(boolean)
   * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getTipoAtributo_Array()
   * @model
   * @generated
   */
  boolean isArray();

  /**
   * Sets the value of the '{@link cl.ejemplo.entidades.entidades.TipoAtributo#isArray <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' attribute.
   * @see #isArray()
   * @generated
   */
  void setArray(boolean value);

  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see cl.ejemplo.entidades.entidades.EntidadesPackage#getTipoAtributo_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link cl.ejemplo.entidades.entidades.TipoAtributo#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

} // TipoAtributo
