/*
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.parser.antlr;

import cl.ejemplo.entidades.parser.antlr.internal.InternalEntidadesParser;
import cl.ejemplo.entidades.services.EntidadesGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EntidadesParser extends AbstractAntlrParser {

	@Inject
	private EntidadesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEntidadesParser createParser(XtextTokenStream stream) {
		return new InternalEntidadesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public EntidadesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EntidadesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
