/*
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EntidadesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("cl/ejemplo/entidades/parser/antlr/internal/InternalEntidades.tokens");
	}
}
