/**
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.entidades.impl;

import cl.ejemplo.entidades.entidades.Atributo;
import cl.ejemplo.entidades.entidades.Entidad;
import cl.ejemplo.entidades.entidades.EntidadesPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entidad</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link cl.ejemplo.entidades.entidades.impl.EntidadImpl#getName <em>Name</em>}</li>
 *   <li>{@link cl.ejemplo.entidades.entidades.impl.EntidadImpl#getSuperTipo <em>Super Tipo</em>}</li>
 *   <li>{@link cl.ejemplo.entidades.entidades.impl.EntidadImpl#getAtributos <em>Atributos</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EntidadImpl extends MinimalEObjectImpl.Container implements Entidad
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSuperTipo() <em>Super Tipo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuperTipo()
   * @generated
   * @ordered
   */
  protected Entidad superTipo;

  /**
   * The cached value of the '{@link #getAtributos() <em>Atributos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtributos()
   * @generated
   * @ordered
   */
  protected EList<Atributo> atributos;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntidadImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntidadesPackage.Literals.ENTIDAD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntidadesPackage.ENTIDAD__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Entidad getSuperTipo()
  {
    if (superTipo != null && superTipo.eIsProxy())
    {
      InternalEObject oldSuperTipo = (InternalEObject)superTipo;
      superTipo = (Entidad)eResolveProxy(oldSuperTipo);
      if (superTipo != oldSuperTipo)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, EntidadesPackage.ENTIDAD__SUPER_TIPO, oldSuperTipo, superTipo));
      }
    }
    return superTipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidad basicGetSuperTipo()
  {
    return superTipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuperTipo(Entidad newSuperTipo)
  {
    Entidad oldSuperTipo = superTipo;
    superTipo = newSuperTipo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntidadesPackage.ENTIDAD__SUPER_TIPO, oldSuperTipo, superTipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Atributo> getAtributos()
  {
    if (atributos == null)
    {
      atributos = new EObjectContainmentEList<Atributo>(Atributo.class, this, EntidadesPackage.ENTIDAD__ATRIBUTOS);
    }
    return atributos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EntidadesPackage.ENTIDAD__ATRIBUTOS:
        return ((InternalEList<?>)getAtributos()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EntidadesPackage.ENTIDAD__NAME:
        return getName();
      case EntidadesPackage.ENTIDAD__SUPER_TIPO:
        if (resolve) return getSuperTipo();
        return basicGetSuperTipo();
      case EntidadesPackage.ENTIDAD__ATRIBUTOS:
        return getAtributos();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EntidadesPackage.ENTIDAD__NAME:
        setName((String)newValue);
        return;
      case EntidadesPackage.ENTIDAD__SUPER_TIPO:
        setSuperTipo((Entidad)newValue);
        return;
      case EntidadesPackage.ENTIDAD__ATRIBUTOS:
        getAtributos().clear();
        getAtributos().addAll((Collection<? extends Atributo>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EntidadesPackage.ENTIDAD__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EntidadesPackage.ENTIDAD__SUPER_TIPO:
        setSuperTipo((Entidad)null);
        return;
      case EntidadesPackage.ENTIDAD__ATRIBUTOS:
        getAtributos().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EntidadesPackage.ENTIDAD__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EntidadesPackage.ENTIDAD__SUPER_TIPO:
        return superTipo != null;
      case EntidadesPackage.ENTIDAD__ATRIBUTOS:
        return atributos != null && !atributos.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //EntidadImpl
