/**
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.entidades.impl;

import cl.ejemplo.entidades.entidades.Entidad;
import cl.ejemplo.entidades.entidades.EntidadesPackage;
import cl.ejemplo.entidades.entidades.TipoAtributo;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tipo Atributo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link cl.ejemplo.entidades.entidades.impl.TipoAtributoImpl#getEntidad <em>Entidad</em>}</li>
 *   <li>{@link cl.ejemplo.entidades.entidades.impl.TipoAtributoImpl#isArray <em>Array</em>}</li>
 *   <li>{@link cl.ejemplo.entidades.entidades.impl.TipoAtributoImpl#getLength <em>Length</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TipoAtributoImpl extends MinimalEObjectImpl.Container implements TipoAtributo
{
  /**
   * The cached value of the '{@link #getEntidad() <em>Entidad</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntidad()
   * @generated
   * @ordered
   */
  protected Entidad entidad;

  /**
   * The default value of the '{@link #isArray() <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isArray()
   * @generated
   * @ordered
   */
  protected static final boolean ARRAY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isArray() <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isArray()
   * @generated
   * @ordered
   */
  protected boolean array = ARRAY_EDEFAULT;

  /**
   * The default value of the '{@link #getLength() <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLength()
   * @generated
   * @ordered
   */
  protected static final int LENGTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLength() <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLength()
   * @generated
   * @ordered
   */
  protected int length = LENGTH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TipoAtributoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntidadesPackage.Literals.TIPO_ATRIBUTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Entidad getEntidad()
  {
    if (entidad != null && entidad.eIsProxy())
    {
      InternalEObject oldEntidad = (InternalEObject)entidad;
      entidad = (Entidad)eResolveProxy(oldEntidad);
      if (entidad != oldEntidad)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, EntidadesPackage.TIPO_ATRIBUTO__ENTIDAD, oldEntidad, entidad));
      }
    }
    return entidad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidad basicGetEntidad()
  {
    return entidad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntidad(Entidad newEntidad)
  {
    Entidad oldEntidad = entidad;
    entidad = newEntidad;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntidadesPackage.TIPO_ATRIBUTO__ENTIDAD, oldEntidad, entidad));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isArray()
  {
    return array;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArray(boolean newArray)
  {
    boolean oldArray = array;
    array = newArray;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntidadesPackage.TIPO_ATRIBUTO__ARRAY, oldArray, array));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getLength()
  {
    return length;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLength(int newLength)
  {
    int oldLength = length;
    length = newLength;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EntidadesPackage.TIPO_ATRIBUTO__LENGTH, oldLength, length));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EntidadesPackage.TIPO_ATRIBUTO__ENTIDAD:
        if (resolve) return getEntidad();
        return basicGetEntidad();
      case EntidadesPackage.TIPO_ATRIBUTO__ARRAY:
        return isArray();
      case EntidadesPackage.TIPO_ATRIBUTO__LENGTH:
        return getLength();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EntidadesPackage.TIPO_ATRIBUTO__ENTIDAD:
        setEntidad((Entidad)newValue);
        return;
      case EntidadesPackage.TIPO_ATRIBUTO__ARRAY:
        setArray((Boolean)newValue);
        return;
      case EntidadesPackage.TIPO_ATRIBUTO__LENGTH:
        setLength((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EntidadesPackage.TIPO_ATRIBUTO__ENTIDAD:
        setEntidad((Entidad)null);
        return;
      case EntidadesPackage.TIPO_ATRIBUTO__ARRAY:
        setArray(ARRAY_EDEFAULT);
        return;
      case EntidadesPackage.TIPO_ATRIBUTO__LENGTH:
        setLength(LENGTH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EntidadesPackage.TIPO_ATRIBUTO__ENTIDAD:
        return entidad != null;
      case EntidadesPackage.TIPO_ATRIBUTO__ARRAY:
        return array != ARRAY_EDEFAULT;
      case EntidadesPackage.TIPO_ATRIBUTO__LENGTH:
        return length != LENGTH_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (array: ");
    result.append(array);
    result.append(", length: ");
    result.append(length);
    result.append(')');
    return result.toString();
  }

} //TipoAtributoImpl
