/**
 * generated by Xtext 2.21.0
 */
package cl.ejemplo.entidades.generator;

import cl.ejemplo.entidades.entidades.Entidad;
import com.google.common.collect.Iterators;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class EntidadesGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final Function1<Entidad, String> _function = (Entidad it) -> {
      return it.getName();
    };
    String _join = IteratorExtensions.join(IteratorExtensions.<Entidad, String>map(Iterators.<Entidad>filter(resource.getAllContents(), Entidad.class), _function), ", ");
    String _plus = ("People to greet: " + _join);
    fsa.generateFile("greetings.txt", _plus);
  }
}
